# Generated by Django 4.2.7 on 2023-12-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transferaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferaccount',
            old_name='transfer_acc_username',
            new_name='transfer_acc_no',
        ),
    ]
