# Generated by Django 4.2.7 on 2023-12-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_bankrupt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bankrupt',
            field=models.BooleanField(default=True),
        ),
    ]
