# Generated by Django 4.2.7 on 2023-12-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_bankrupt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
